#!/bin/bash

# See https://medium.com/@artur.klauser/building-multi-architecture-docker-images-with-buildx-27d80f7e2408

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$SCRIPT_DIR/bash-helpers.sh"

#argv=()
group=""

while [[ $# -gt 0 ]]; do
  case $1 in
    -g|--group)
      shift; group="$1"; shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*|--*)
      option="$1"; shift
      usage
      echo >&2
      echo "Unrecognized option $option" >&2
      exit 1
      ;;
    *)
      break
      # argv+=("$1"); shift
      ;;
  esac
done

#set -- "${argv[@]}"

if [ -z "$group" ]; then
  echo "A group must be provided with -g or --group" >&2
  exit 1
fi

if [[ $# -eq 0 ]]; then
  set -- bash
fi

run_with_group "$group" "$@"
